Feature/new trip structure
SmartcitySantiagoChile/dataUploader pull request #12
Opened 2023-03-22 06:22 UTC by Bastianleaf

# Nueva Estructura para Archivos .trip

## 🗂 Nuevos archivos
`tests/testTrip.py`
- Se agregan los archivos `2022-10-01.trip`, `2022-10-01.trip.gz`, `2022-10-01.trip.zip`con fin de probar el correcto funcionamiento del mapping.

## 💻 Mapping
`datauploader/mappings/trip-template.json`
- Se agregan todas las columnas nuevas del archivo.
- Por temas semánticos, se cambia nombre de columna de archivo por otro. Ej: `netapassinbajada -> n_etapas_sin_bajada`

## 🚌 Parsing de valores
 `datauploader/uploader/datafile.py`
- Se agregan métodos para parsear de forma más limpia los valores de los archivos.

` tests/testMain.py`
- Se agregan tests para los nuevos métodos anteriormente mencionados.

`datauploader/uploader/trip.py`
- Se agregan nuevas columnas de los archivos posteriores a 2022-09-30.
- Se agrega lógica de selección de campo `fieldnames`dependiendo de la fecha.
- Se agrega parsing para compatibilizar columnas con nombres nuevos pero que ya existían anteriormente. Ej: `tiempo_subida1 -> tiempo_subida_1`

## 🐳 Tests en docker
`docker/Dockerfile`
- Se agrega la descarga e instalación de **[shunit2](https://github.com/kward/shunit2)**: aplicación que implementa unit tests
para lenguaje bash.
- Se agrega archivo `docker/test-elasticsearch.sh` contenedor de los tests.

`docker/entrypoint.sh`
- Se modifica el test a elasticsearch por la ejecución de los tests unitarios de `docker/test-elasticsearch.sh` por medio de `shunit2`.

`docker/test-elasticsearch.sh`
- Nuevo archivo que contiene todos los tests relacionados a carga de archivos en `elasticsearch`.
- Como aproximación inicial hay un test unitario por cada índice y por cada archivo distinto de índice. Los tests evalúan que la carga se haya realizado correctamente por medio de la revisión de la respuesta a la llamada `curl`.

## ⬆ Nueva versión
`setup.py`
- Se actualiza a la versión `2.0.26`

2023-03-22 23:06 UTC, felipinbombin requested changes
Me parecen bien los cambios en general. 

Revisando, me di cuenta que los tests no eran tan precisos, y me refiero a que no detectaba el caso cuando se creó el índice pero no se pudieron subir datos, eso lo cambié incorporando un check sobre el atributo total, para ver cuantos datos hay en el índice.

Tareas adicionales que hay que realizar:
- identificar que campos no se usan en los filtros, para esos casos, incorporar el atributo `"index": false`. Esto hará que elasticsearch entregue estos datos en los resultados pero no incorporará índices sobre estos, ahorrando espacio.
- tengo la duda de si usaste algún criterio para seleccionar los tipos de las nuevas columnas, por ejemplo: Me basé en los campos anteriores, revise los datos en los archivos. Me queda la duda del tipo con los siguientes campos: `id_viaje`, `mediahora_inicio_viaje_hora`, 'mediahora_fin_viaje_hora'

2023-03-22 23:06 UTC, felipinbombin commented on datauploader/mappings/trip-template.json
> -        },
estos atributos se quitaron ¿por qué? fueron reemplazados por alguno de los nuevos? no logro encontrar uno con el mismo nombre, si fue reemplazado por uno nuevo en el nombre, hay que tener presente en el server que se deben actualizar sus valores

2023-03-22 23:06 UTC, felipinbombin commented on datauploader/uploader/trip.py
> +                self.fieldnames = value
dado que el diccionario no asegura un orden de las keys, pienso que esto podría generar un problema si lee primero la fecha del 2022-09-30 y luego 1970-01-01. En este caso se quedaría con unas columnas equivocadas. Lo otro, es hacer la comparación `>=`.  para que el diccionario se pueda leer como "Esta es la estructura que se usa a partir de esta fecha". En la forma actual me hace pensar en el primer día en que esto es válido

2023-03-22 23:06 UTC, felipinbombin commented on docker/test-elasticsearch.sh
> +
esto quedó bkn, no cachaba que existía 👍🏻

2023-03-23 01:48 UTC, Bastianleaf commented on datauploader/mappings/trip-template.json
> -        },
Efectivamente, pasé a llevar esos atributos del mapping, pero no debían ser borrados. Ahora los restauro.

2023-03-23 01:49 UTC, Bastianleaf commented on datauploader/uploader/trip.py
> +                self.fieldnames = value
Tienes razón, haré la modificación en base a esto.

2023-03-23 01:50 UTC, Bastianleaf commented on docker/test-elasticsearch.sh
> +
Efectivamente, parece ser una forma bien práctica para hacer test en bash. Vi la modificación que hiciste en los tests y me parece bien.

2023-03-23 02:03 UTC, Bastianleaf commented
> Me parecen bien los cambios en general.
> 
> Revisando, me di cuenta que los tests no eran tan precisos, y me refiero a que no detectaba el caso cuando se creó el índice pero no se pudieron subir datos, eso lo cambié incorporando un check sobre el atributo total, para ver cuantos datos hay en el índice.
> 
> Tareas adicionales que hay que realizar:
> 
> * identificar que campos no se usan en los filtros, para esos casos, incorporar el atributo `"index": false`. Esto hará que elasticsearch entregue estos datos en los resultados pero no incorporará índices sobre estos, ahorrando espacio.
> * tengo la duda de si usaste algún criterio para seleccionar los tipos de las nuevas columnas, por ejemplo: Me basé en los campos anteriores, revise los datos en los archivos. Me queda la duda del tipo con los siguientes campos: `id_viaje`, `mediahora_inicio_viaje_hora`, 'mediahora_fin_viaje_hora'

1. Ok, verificaré todos los campos que no usan filtros.
2. Sí, mi criterio fue el tipo de dato que se usó de ejemplo en el [informe adjunto](https://docs.google.com/document/d/1zG7U9PdKtrqNeDvfwOYxvub3fj3LuPMUqaGTRmKQ7y0/edit#) .
- Para el caso de `mediahora_inicio_viaje_hora` y  `mediahora_fin_viaje_hora`también revisé el archivo y efectivamente son en formato HH:mm:ss.
- Para el caso de `id_viaje` no había mucha pista. Pero la descripción del informe dice `Correlativo del viaje de la tarjeta bip!` . Esto me hizo deducir que puede tomar valores en el rango [1,3] (3 es el máximo para el caso de micro -> metro -> micro).

- Al volver a revisar los datos me queda la duda si es que las columnas desde `dt1` hasta `dveh_eucfinal` deben ser de tipo "integer"o "float" (en el informe solo `dt1` tiene formato float, pero me hace sentido que estos otros atributos también).

2023-03-23 07:39 UTC, felipinbombin commented
> > Me parecen bien los cambios en general.
> > Revisando, me di cuenta que los tests no eran tan precisos, y me refiero a que no detectaba el caso cuando se creó el índice pero no se pudieron subir datos, eso lo cambié incorporando un check sobre el atributo total, para ver cuantos datos hay en el índice.
> > Tareas adicionales que hay que realizar:
> > 
> > * identificar que campos no se usan en los filtros, para esos casos, incorporar el atributo `"index": false`. Esto hará que elasticsearch entregue estos datos en los resultados pero no incorporará índices sobre estos, ahorrando espacio.
> > * tengo la duda de si usaste algún criterio para seleccionar los tipos de las nuevas columnas, por ejemplo: Me basé en los campos anteriores, revise los datos en los archivos. Me queda la duda del tipo con los siguientes campos: `id_viaje`, `mediahora_inicio_viaje_hora`, 'mediahora_fin_viaje_hora'
> 
> 1. Ok, verificaré todos los campos que no usan filtros.
> 2. Sí, mi criterio fue el tipo de dato que se usó de ejemplo en el [informe adjunto](https://docs.google.com/document/d/1zG7U9PdKtrqNeDvfwOYxvub3fj3LuPMUqaGTRmKQ7y0/edit#) .
> 
> * Para el caso de `mediahora_inicio_viaje_hora` y  `mediahora_fin_viaje_hora`también revisé el archivo y efectivamente son en formato HH:mm:ss.
> * Para el caso de `id_viaje` no había mucha pista. Pero la descripción del informe dice `Correlativo del viaje de la tarjeta bip!` . Esto me hizo deducir que puede tomar valores en el rango [1,3] (3 es el máximo para el caso de micro -> metro -> micro).
> * Al volver a revisar los datos me queda la duda si es que las columnas desde `dt1` hasta `dveh_eucfinal` deben ser de tipo "integer"o "float" (en el informe solo `dt1` tiene formato float, pero me hace sentido que estos otros atributos también).

yap bkn, entonces faltaría lo siguiente:

- revisar atributos viejos del índice trip, y para aquellos que no se usan en los filtros incorporar el atributo `index: false`. Esta info se saca del proyecto del server (revisar app esapi)
- me gustaría que hicieras una identificación de dominio de los valores para el campo `id_viaje` para corroborar que esto funcionará. Un pseudocódigo que permite saber esto sería: `cat nombre_archivo.csv | cut -d '|' -f13 | sort | uniq` donde `'|'` es el separador de columnas y -f13 indica que se devolverá la columna 13, hay que ver a qué columna corresponde el atributo `id_viaje`. El resultado serán todos los valores distintos que toma la columna en el archivo, pienso que con revisar un archivo podremos saberlo.

con esas dos cosas podemos dar por aprobado el PR 👍🏻

2023-03-23 16:05 UTC, Bastianleaf commented
> > > Me parecen bien los cambios en general.
> > > Revisando, me di cuenta que los tests no eran tan precisos, y me refiero a que no detectaba el caso cuando se creó el índice pero no se pudieron subir datos, eso lo cambié incorporando un check sobre el atributo total, para ver cuantos datos hay en el índice.
> > > Tareas adicionales que hay que realizar:
> > > 
> > > * identificar que campos no se usan en los filtros, para esos casos, incorporar el atributo `"index": false`. Esto hará que elasticsearch entregue estos datos en los resultados pero no incorporará índices sobre estos, ahorrando espacio.
> > > * tengo la duda de si usaste algún criterio para seleccionar los tipos de las nuevas columnas, por ejemplo: Me basé en los campos anteriores, revise los datos en los archivos. Me queda la duda del tipo con los siguientes campos: `id_viaje`, `mediahora_inicio_viaje_hora`, 'mediahora_fin_viaje_hora'
> > 
> > 
> > 
> > 1. Ok, verificaré todos los campos que no usan filtros.
> > 2. Sí, mi criterio fue el tipo de dato que se usó de ejemplo en el [informe adjunto](https://docs.google.com/document/d/1zG7U9PdKtrqNeDvfwOYxvub3fj3LuPMUqaGTRmKQ7y0/edit#) .
> > 
> > 
> > * Para el caso de `mediahora_inicio_viaje_hora` y  `mediahora_fin_viaje_hora`también revisé el archivo y efectivamente son en formato HH:mm:ss.
> > * Para el caso de `id_viaje` no había mucha pista. Pero la descripción del informe dice `Correlativo del viaje de la tarjeta bip!` . Esto me hizo deducir que puede tomar valores en el rango [1,3] (3 es el máximo para el caso de micro -> metro -> micro).
> > * Al volver a revisar los datos me queda la duda si es que las columnas desde `dt1` hasta `dveh_eucfinal` deben ser de tipo "integer"o "float" (en el informe solo `dt1` tiene formato float, pero me hace sentido que estos otros atributos también).
> 
> yap bkn, entonces faltaría lo siguiente:
> 
> * revisar atributos viejos del índice trip, y para aquellos que no se usan en los filtros incorporar el atributo `index: false`. Esta info se saca del proyecto del server (revisar app esapi)
> * me gustaría que hicieras una identificación de dominio de los valores para el campo `id_viaje` para corroborar que esto funcionará. Un pseudocódigo que permite saber esto sería: `cat nombre_archivo.csv | cut -d '|' -f13 | sort | uniq` donde `'|'` es el separador de columnas y -f13 indica que se devolverá la columna 13, hay que ver a qué columna corresponde el atributo `id_viaje`. El resultado serán todos los valores distintos que toma la columna en el archivo, pienso que con revisar un archivo podremos saberlo.
> 
> con esas dos cosas podemos dar por aprobado el PR 👍🏻

Perfecto, haré ambas cosas.

2023-03-24 02:37 UTC, Bastianleaf commented
- Se corrige `id_viaje` a short. Efectivamente toma valores enteros positivos más grandes. 
- Se agrega `"index": false` a los atributos faltantes.

2023-03-24 06:51 UTC, felipinbombin approved these changes
Super. Se ve todo bien a mí parecer.👍. Tareas siguientes:
- sacar un release en github de esta versión
- actualizar el proyecto del server con esta nueva versión
- revisar que las vistas de viajes funcionan, eso es:
    - ir a una página de la sección de viajes
    - generar una o más consultas que permitan usar todos los filtros
    - Repetir lo anterior hasta acabarlas todas
- modificar procedimiento de descarga de datos de viaje para que ahora incluya todos los atributos nuevos 
- modificar tests o agregar nuevos si es necesario

2023-03-24 18:26 UTC, merged