Feature/new profile columns
SmartcitySantiagoChile/dataUploader pull request #4
Opened 2021-05-10 16:35 UTC by Bastianleaf

Se agregan las nuevas columnas y corrigen tests

2021-05-10 17:23 UTC, felipinbombin requested changes

2021-05-10 17:23 UTC, felipinbombin commented on datauploader/uploader/profile.py
> +            "uniformDistributionMethod": int(row['uniformDistributionMethod'])
creo que esto no funciona para los datos antiguos, me refiero a archivos que no tienen las columnas de evasión y estas tres nuevas  columnas ¿es así? según entiendo se caería

2021-05-10 17:23 UTC, felipinbombin commented on tests/testProfile.py
> +        file_name_list = ['2020-11-30.profile', '2020-11-30.profile.gz', '2020-11-30.profile.zip']
¿por qué quitar los archivos viejos de prueba? son los que nos permiten ver que esto funciona para archivos que no tienen las columnas de evasión ¿o me equivoco?

2021-05-10 17:27 UTC, Bastianleaf commented on datauploader/uploader/profile.py
> +            "uniformDistributionMethod": int(row['uniformDistributionMethod'])
Correcto, haré la corrección, en ese caso, cuales son los valores que debería almacenarse en caso de no existir?
-1?

2021-05-10 17:28 UTC, Bastianleaf commented on tests/testProfile.py
> +        file_name_list = ['2020-11-30.profile', '2020-11-30.profile.gz', '2020-11-30.profile.zip']
Cierto, lo corregiré.

2021-05-10 17:33 UTC, felipinbombin commented on datauploader/uploader/profile.py
> +            "uniformDistributionMethod": int(row['uniformDistributionMethod'])
si, -1 está bien

2021-05-10 17:46 UTC, Bastianleaf commented
Corregidos los cambios

2021-05-10 18:53 UTC, felipinbombin commented on tests/files/2017-07-31-with-evasion.profile
> +operator|route|userRoute|licensePlate|authStopCode|userStopName|expeditionStartTime|expeditionEndTime|fulfillment|expeditionStopOrder|expeditionDayId|stopDistanceFromPathStart|#Subidas|#SubidasLejana
estos archivos deberían tener las nuevas columnas de evasión y no las veo ¿están incorporadas?

2021-05-11 19:55 UTC, Bastianleaf commented on tests/files/2017-07-31-with-evasion.profile
> +operator|route|userRoute|licensePlate|authStopCode|userStopName|expeditionStartTime|expeditionEndTime|fulfillment|expeditionStopOrder|expeditionDayId|stopDistanceFromPathStart|#Subidas|#SubidasLejana
CIerto, ya está corregido. Para mayor claridad los archivos .profile son sin las columnas de evasión, los archivos with-evasion.profile son los archivos con las columnas de evasión agregadas anteriormentes y los archivos -with-evasion-2.profile son los archivos con las nuevas columnas actuales.

2021-05-12 14:14 UTC, felipinbombin approved these changes

2021-05-12 14:17 UTC, merged